### ISSUE TITLE
Zombie fail causes crash

### ISSUE THREAD

**Issue by mateoconlechuga** [stbeaumont98/Zombie-Chase-CE#1]
Need to look into this more, but I am not sure what could be the case yet.

**Comment by spenceboy98** [comment]
The program size being huge is probably due to the huge ZombieFail sprite. Could that be what's causing the crash? I'd be fine with making a smaller sprite and scaling it up.

**Comment by mateoconlechuga** [comment]
Yeah, it's about 13000 of the 16000 bytes. It's not too big of an issue, but it's generally a good idea to make things as small as possible :)

**Comment by mateoconlechuga** [comment]
I don't believe that was what was causing the crash; I moved some things around because it was setting the variable to 0, but then attempting to use it unitialized. Should be fine now
